apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsel-demo-api
  labels:
    app: marsel-demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marsel-demo-api
  template:
    metadata:
      labels:
        app: marsel-demo-api
    spec:
      containers:
      - name: marsel-demo-api
        image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/apiapp:marsel-1.1
        ports:
        - containerPort: 80
