apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsel-demo-web
  labels:
    app: marsel-demo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marsel-demo-web
  template:
    metadata:
      labels:
        app: marsel-demo-web
    spec:
      containers:
      - name: marsel-demo-web
        image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/webapp:marsel
        ports:
        - containerPort: 80
